Feature/uwang 174
Bluhabit/uwang-rest-account pull request #10
Opened 2024-03-21 15:44 UTC by BilyHakim

[FEATURE][UWANG-173] - membuat feature GetListUserByQuery

#### Description

> Description of features, bugs, improvements or any changes in this MR.

#### Ticket Reference(s)

(https://bluehabit.atlassian.net/browse/UWANG-174)

#### Validation

##### UI Changes

> Screenshot or video of UI-related changes

##### Coverage

> Test coverage screenshot.

N/A

#### Note(s)

> Mention other user or extra note unrelated to the MR here.

[UWANG-173]: https://bluehabit.atlassian.net/browse/UWANG-173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-03-22 18:06 UTC, azkifairuz requested changes
punteng bang

2024-03-22 18:06 UTC, azkifairuz commented on routes/user/user.go
> +
izin nambahin bang, biar aman dibikin valdasi buat cek kalo misal namenya atau querynya gada didatabse
```
query , ok := ctx.DefaultQuery("query", "")
if !ok {
		ctx.JSON(200, response.BadRequest("", "User tidak ditemukan"))
	}

```

2024-03-22 22:31 UTC, azkifairuz requested changes

2024-03-22 22:31 UTC, azkifairuz commented on repositories/user/user-repository.go
> +	err := repo.db.Where("name LIKE ?", "%"+query+"%").Find(&userCredential).Error
maaf bang, ditable userCredential gada name, adanaya full_name atau username. jdi nnti hasilnya "tidak menemukan data" terus karena dia g nemu fieldnya


**field yg ada **
```
type UserCredential struct {
	ID           string    `gorm:"column:id;primaryKey;default:8a4d80da-ec44-41db-b1ca-b7020d1418d4" json:"id"`
	Email        string    `gorm:"column:email;not null" json:"email"`
	Password     string    `gorm:"column:password;not null" json:"password"`
	Username     string    `gorm:"column:username;not null" json:"username"`
	FullName     string    `gorm:"column:full_name;not null" json:"full_name"`
	DateOfBirth  time.Time `gorm:"column:date_of_birth" json:"date_of_birth"`
	Gender       string    `gorm:"column:gender" json:"gender"`
	Status       string    `gorm:"column:status;not null" json:"status"`
	AuthProvider string    `gorm:"column:auth_provider;not null" json:"auth_provider"`
	CreatedAt    time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	Deleted      bool      `gorm:"column:deleted;not null" json:"deleted"`
}
```

2024-03-23 03:09 UTC, BilyHakim commented on routes/user/user.go
> +
Oke good, udh gw tambahin ya

2024-03-23 17:20 UTC, azkifairuz approved these changes
kelass bang, tinggal nunggu bang trian acc

2024-03-25 18:39 UTC, merged